kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive4
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 917Gi
  accessModes:
      - ReadWriteOnce
  local:
    path: "/drive4"