kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 917Gi
  accessModes:
      - ReadWriteOnce
  hostPath:
    path: "/drive4"