kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive1
spec:
  storageClassName: local-storage
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube
  capacity:
    storage: 932Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
      - ReadWriteOnce
  local:
    path: "/drive1"