kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive3
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2.8Ti
  accessModes:
      - ReadWriteOnce
  local:
    path: "/drive3"