kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2.8Ti
  accessModes:
      - ReadWriteOnce
  hostPath:
    path: "/drive3"