kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive2
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1.9Ti
  persistentVolumeReclaimPolicy: Delete
  accessModes:
      - ReadWriteOnce
  local:
    path: "/drive2"