kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1.9Ti
  accessModes:
      - ReadWriteOnce
  hostPath:
    path: "/drive2"