kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive1
    annotations:
  labels:
    type: local
spec:
  storageClassName: local-storage
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelector:
          kubernetes.io/hostname: minikube
  capacity:
    storage: 932Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
      - ReadWriteOnce
  local:
    path: "/drive1"