kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 932Gi
  accessModes:
      - ReadWriteOnce
  hostPath:
    path: "/drive1"