kind: PersistentVolume
apiVersion: v1
metadata:
  name: pms-pv-drive1
    annotations:
    "volume.alpha.kubernetes.io/node-affinity": '{
      "requiredDuringSchedulingIgnoredDuringExecution": {
        "nodeSelectorTerms": [
          { "matchExpressions": [
            { "key": "kubernetes.io/hostname",
              "operator": "In",
              "values": ["minikube"]
            }
          ]}
         ]}
        }'
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 932Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
      - ReadWriteOnce
  local:
    path: "/drive1"