apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-deployment
  labels:
    app: plex-media-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plex-media-server
    spec:
      containers:
      - name: pms
        image: plexinc/pms-docker:latest
        ports:
        - containerPort: 32400
      volumes:
      - name: work-volume
        persistentVolumeClaim:
          claimName: report-api-pvc
          #  claimName: report-api-pvc
