apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pms-deployment
  labels:
    app: plex-media-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plex-media-server
    spec:
      containers:
      - name: pms
        image: plexinc/pms-docker:latest
        ports:
        - containerPort: 32400
        volumeMounts:
        - name: drive1
          mountPath: /drive1
        - name: drive2
          mountPath: /drive2
        - name: drive3
          mountPath: /drive3
        - name: drive4
          mountPath: /drive4


      volumes:
      - name: drive1
        persistentVolumeClaim:
          claimName: pms-pvc-drive1

      - name: drive2
        persistentVolumeClaim:
          claimName: pms-pvc-drive2

      - name: drive3
        persistentVolumeClaim:
          claimName: pms-pvc-drive3

      - name: drive4
        persistentVolumeClaim:
          claimName: pms-pvc-drive4
