apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-deployment
  labels:
    app: plex-media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-media-server
  template:
    metadata:
      labels:
        app: plex-media-server
    spec:
      containers:
      - name: plexinc/pms-docker
        image: plexinc/pms-docker:latest
        ports:
        - containerPort: 32400