apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-deployment
  labels:
    app: plex-media-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plex-media-server
    spec:
      containers:
      - name: pms
        image: plexinc/pms-docker:latest
        ports:
        - containerPort: 32400
      volumes:
      - name: drive1
        persistentVolumeClaim:
          claimName: pms-pvc-drive1
          
      - name: drive2
        persistentVolumeClaim:
          claimName: pms-pvc-drive2

      - name: drive3
        persistentVolumeClaim:
          claimName: pms-pvc-drive3

      - name: drive4
        persistentVolumeClaim:
          claimName: pms-pvc-drive4
