apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pms-deployment
  labels:
    app: plex-media-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plex-media-server
    spec:
      containers:
      - name: pms
        image: plexinc/pms-docker:latest
        ports:
        - containerPort: 32400
        volumeMounts:
        - mountPath: /drive1
          name: pms-pv-drive1
        - mountPath: /drive2
          name: pms-pv-drive2
        - mountPath: /drive3
          name: pms-pv-drive3
        - mountPath: /drive4
          name: pms-pv-drive4
      volumes:
      - name: pms-pv-drive1
        hostPath:
          path: '/drive1'
      - name: pms-pv-drive2
        hostPath:
          path: '/drive2'
      - name: pms-pv-drive3
        hostPath:
          path: '/drive3'
      - name: pms-pv-drive4
        hostPath:
          path: '/drive4'
